name: Anna Capitano
favicon: null
layout_spectrum: 0.8640801617875695
typography_spectrum: 0.408463240833953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8170462653506547
  lightness: 0.1968149384483695
  saturation: 0.6705319546163082
  rhythmicContrast: 0.4750730940140784
purpose: []
